{{- if .Values.enabled }}
{{- if .Values.rhsso }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    description: ConfigMap providing service ca bundle.
    service.beta.openshift.io/inject-cabundle: 'true'
  labels:
    application: {{ .Values.application_name }}
  name: {{ .Values.application_name }}-service-ca
{{- end }}
{{- end }}
