{{- if .Values.enabled }}
{{- if .Values.rhsso }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-jgroups-secret
  labels:
    application: {{ .Values.application_name }}
  name: {{ .Values.application_name }}-ping
spec:
  clusterIP: None
  ports:
    - name: ping
      port: 8888
  selector:
    deploymentConfig: {{ .Values.application_name }}
{{- end }}
{{- end }}
