{{- if .Values.enabled }}
{{- if .Values.smart_router }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    application: {{ .Values.application_name }}
    rhpam: {{ .Values.rhpam.version | quote }}
    service: {{ .Values.application_name }}-smartrouter
  name: {{ .Values.application_name }}-smartrouter-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.smart_router.resources.storage_request }}
{{- end }}
{{- end }}