{{- if .Values.enabled }}
{{- if .Values.kie_server }}
---
apiVersion: v1
kind: RoleBinding
metadata:
  labels:
    application: {{ .Values.application_name }}
    rhpam: {{ .Values.rhpam.version | quote }}
  name: {{ .Values.application_name }}-kieserver-view
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: {{ .Values.application_name }}-kieserver
{{- end }}
{{- end }}