{{- if .Values.enabled }}
{{- if .Values.business_central.expose }}
---
apiVersion: v1
id: insecure-{{ .Values.application_name }}-rhpamcentrmon-http
kind: Route
metadata:
  annotations:
    description: Route for Business Central http service.
    haproxy.router.openshift.io/timeout: 1h
  labels:
    application: {{ .Values.application_name }}
    rhpam: {{ .Values.rhpam.version | quote }}
    service: {{ .Values.application_name }}-rhpamcentrmon
  name: insecure-{{ .Values.application_name }}-rhpamcentrmon
spec:
  host: {{ .Values.business_central.hostname_http }}
  port:
    targetPort: http
  to:
    name: {{ .Values.application_name }}-rhpamcentrmon
{{- end }}
{{- end }}