{{- if .Values.enabled }}
{{- if .Values.rhpam }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application: {{ .Values.application_name }}
    rhpam: {{ .Values.rhpam.version | quote }}
  name: {{ .Values.application_name }}-rhpamsvc
{{- end }}
{{- end }}