---

enabled: true

rhsso_namespace: &rhsso_ns labs-test

application_name: rhsso

rhsso:
  version: "7.4.0.GA"
  replicas: 1
  expose: true
  jgroupClusterPassword: sso74
  admin:
    user: sso
    pass: sso
  service:
    user: sso
    pass: sso
  # realm: redhat
  resources:
    limits:
      memory: "1Gi"
  imagestream:
    namespace: openshift
    name: sso74-openshift-rhel8
    tag: "7.4"
  import:
    secret: realm-keycloak
    filename: realm-keycloak

postgresql:
  version: "10"
  replicas: 1
  jndi: java:jboss/datasources/KeycloakDS
  user: sso
  pass: sso
  name: root
  size: "1Gi"
  imagestream:
    namespace: openshift
    name: postgresql
    tag: "10"

###########
# name: sso
# version: "7.4.0.GA"
jgroupClusterPassword: sso74
admin:
  user: sso
  pass: sso
service:
  user: sso
  pass: sso
realm: redhat

resources:
  limits:
    memory: "1Gi"

imagestream:
  namespace: openshift
  name: sso74-openshift-rhel8
  tag: "7.4"

# database:
#   jndi: java:jboss/datasources/KeycloakDS
#   user: sso
#   pass: sso
#   name: root
#   size: "1Gi"
#   # txIsolation: "TRANSACTION_NONE"
#   # poolSize:
#   #   min: "100"
#   #   max: "1000"
