{{- if .Values.enabled }}
{{- if .Values.kie_server.expose }}
---
apiVersion: v1
id: {{ .Values.application_name }}-kieserver-https
kind: Route
metadata:
  annotations:
    description: Route for First KIE server's https service.
  labels:
    application: {{ .Values.application_name }}
    rhpam: {{ .Values.rhpam.version | quote }}
    service: {{ .Values.application_name }}-kieserver
  name: {{ .Values.application_name }}-kieserver
spec:
  host: {{ .Values.kie_server.hostname_https }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    name: {{ .Values.application_name }}-kieserver
{{- end }}
{{- end }}