{{- if .Values.enabled }}
{{- if .Values.kie_server }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kie_server.credentials.secret }}
  labels:
    application: {{ .Values.application_name }}
    rhpam: {{ .Values.rhpam.version | quote }}
    service: {{ .Values.application_name }}-kieserver
    services.server.kie.org/kie-server-id: {{ .Values.application_name }}-kieserver
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
type: Opaque
data:
  KIE_ADMIN_USER: {{ .Values.kie_server.credentials.user | b64enc | quote }}
  KIE_ADMIN_PWD: {{ .Values.kie_server.credentials.password | b64enc | quote }}
{{- end }}
{{- end }}